import Head from "next/head"
import { ReactNode } from "react"
import Header from "./Header"

interface LayoutInterface {
    children: ReactNode,
    title: string
}

export default function Layout({children, title}: LayoutInterface) {
  return (
    <>
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <main className="main-content">
          {children}
        </main>
    </>
  )
}

