import Head from "next/head";
import { ReactNode } from "react";
import Header from "./Header";
import { useRouter } from "next/router";

interface LayoutInterface {
  children: ReactNode;
  title: string;
  hasBackButton?: boolean;
}

export default function Layout({
  children,
  title,
  hasBackButton,
}: LayoutInterface) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main-content">
        {hasBackButton && <button onClick={router.back}>Retour</button>}
        {children}
      </main>
    </>
  );
}
